name: Linux

on:
  push:
    paths:
      - 'install.sh'
      - '.github/workflows/linux.yml'
  pull_request:
    paths:
      - 'install.sh'
      - '.github/workflows/linux.yml'
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9  # 指定 Python 3 版本

    - name: Install dependencies
      run: |
        sudo apt-get install -y libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libuuid1 libsecret-1-0
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download and Install QQ Software
      run: |
        python3 get_qqnt.py Debianx64
        sudo dpkg -i LinuxQQ.deb
        sudo apt-get install -f

    - name: Run install.sh
      run: |
        chmod +x install.sh
        ./install.sh

    - name: Check output and directory existence
      run: |
        if ! /opt/QQ/qq --logging-enable | grep -q "[LiteLoader]" || [ ! -d "/opt/LiteLoader/data" ]; then
          echo "LiteLoader not found in output or /opt/LiteLoader/data directory does not exist. Test failed."
          exit 1
        else
          echo "LiteLoader found in output and /opt/LiteLoader/data directory exists. Test succeeded."
        fi

    - name: Set up iptables rules
      run: |
        # 阻止访问 GitHub
        sudo iptables -A OUTPUT -d github.com -j REJECT

    - name: Remove LiteLoader directory
      run: |
        if [ -d "/opt/LiteLoader" ]; then
          # 删除目录及其内容
          rm -rf "/opt/LiteLoader"
          echo "LiteLoader directory removed successfully."
        else
          echo "LiteLoader directory does not exist."
        fi

    - name: ReRun install.sh
      run: |
        ./install.sh

    - name: Check output again
      run: |
        if ! /opt/QQ/qq --logging-enable | grep -q "[LiteLoader]" || [ ! -d "/opt/LiteLoader/data" ]; then
          echo "LiteLoader not found in output or /opt/LiteLoader/data directory does not exist. Test failed."
          exit 1
        else
          echo "LiteLoader found in output and /opt/LiteLoader/data directory exists. Test succeeded."
        fi
