name: Windows Continuous Build

on:
  push:
    branches:
      - main  # 替换为你的默认分支名称
    if: contains(github.event.head_commit.message, 'pro-release')  # 提交信息包含 'pro-release' 时触发
  workflow_dispatch:  
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9  # 指定 Python 3 版本
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pyinstaller & Build install_windows_pyinstaller.exe
      run: |
        python -m pip install pyinstaller
        pyinstaller --onefile --uac-admin install_windows.py -n install_windows_pyinstaller

    - name: Upload install_windows_pyinstaller.exe
      uses: actions/upload-artifact@v4
      with:
        name: install_windows_pyinstaller
        path: dist/install_windows_pyinstaller.exe
        
  release:
    needs: build  # 确保构建步骤完成后再执行发布
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: install_windows_pyinstaller  # 下载构件
          
      - name: Deploy continuous
        uses: crowbarmaster/GH-Automatic-Releases@latest
        with:
          repo_token: "${{ secrets.AC_TOKEN }}"
          automatic_release_tag: "continuous"
          prerelease: false
          title: "Continuous Build"
          body: "这是一个持续构建的测试版本，修复了 Issues 中已经提出的问题。"  # 添加描述内容
          files: |
            dist/install_windows_pyinstaller.exe  # 更新文件路径为构件下载后的路径
